#!/usr/bin/env bash
set -eo pipefail

base64decode(){
	echo $1 | base64 -d
}

getBase(){
	local base='aHR0cHM6Ly9jYW1zLmNkbi1zdXJmbGluZS5jb20vY2RuLWVjLw=='
	echo $(base64decode $base)
}

base64encode(){
	echo $1 | base64
}

build(){
	echo $(getBase)$(base64decode $1)
}

surf-n-washout(){
	vlc $(build "ZWMtd2FzaG91dC9jaHVua2xpc3QubTN1OAo=")
}

surf-s-pier(){
	vlc $(build "ZWMtZm9sbHlwaWVyc291dGgvY2h1bmtsaXN0Lm0zdTgK")
}

surf-n-pier(){
	vlc $(build "ZWMtZm9sbHlwaWVybm9ydGgvY2h1bmtsaXN0Lm0zdTgK")
}

surf-hiltonhead(){
	vlc $(build "ZWMtaGlsdG9uaGVhZHN1cmYvY2h1bmtsaXN0Lm0zdTgK")
}

surf-s-washout() {
	vlc $(build "ZWMtd2FzaG91dHNvdXRoL2NodW5rbGlzdC5tM3U4Cg==")
}

surf-frisco(){
	vlc $(build "ZWMtZnJpc2NvcGllci9jaHVua2xpc3QubTN1OAo=")
}

surf-hatteras(){
	vlc $(build "ZWMtY2FwZWhhdHRlcmFzL2NodW5rbGlzdC5tM3U4Cg==")
}

surf-s-turns(){
	vlc $(build "ZWMtcm9kYW50aGUvY2h1bmtsaXN0Lm0zdTgK")
}

surf-bogue(){
	vlc $(build "ZWMtYm9ndWVpbmxldHBpZXIvY2h1bmtsaXN0Lm0zdTgK")
}

surf-cocoa(){
	vlc $(build "ZWMtY29jb2FiZWFjaHBpZXJzcy9jaHVua2xpc3QubTN1OAo=")	
}

surf-indiatlantic(){
	vlc $(build "ZWMtaW5kaWFsYW50aWNub3J0aC9jaHVua2xpc3QubTN1OAo=")	
}

surf-st-augustine-a-st(){
	vlc $(build "ZWMtc2FpbnRhdWd1c3QvY2h1bmtsaXN0Lm0zdTgK")
}

surf-st-augustine(){
	vlc $(build "ZWMtc3RhdWd1c3RpbmUvY2h1bmtsaXN0Lm0zdTgK")
}

surf-new-smyrna(){
	vlc $(build "ZWMtbmV3c215L2NodW5rbGlzdC5tM3U4Cg==")
}
surf-flagler(){
	vlc $(build "ZWMtZmxhZ2xlcmJlYWNoL2NodW5rbGlzdC5tM3U4Cg==")
}
surf-sebastian-inlet(){
	vlc $(build "ZWMtc2ViYXN0aWFuaW5sZXQvY2h1bmtsaXN0Lm0zdTgK")
}

surf-jacksonville(){
	vlc $(build "ZWMtamF4cGllcnNzL2NodW5rbGlzdC5tM3U4Cg==")
}

surf-jacksonville-18(){
	vlc $(build "ZWMtamFja3NvbnZpbGxlL2NodW5rbGlzdC5tM3U4Cg==")
}

help(){
	typeset -f | grep surf | awk '/ \(\) $/ {print $1}'
}

main(){
	if declare -f "$1" > /dev/null;
	then
		$1
	else
		echo "Break not defined. Please choose on the following:";
		help
	fi
}

main "$@"