#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
export PATH="$PATH:/home/thomas/.badevops/bin"
autoload -U +X bashcompinit && bashcompinit
for __bootstrap_autofile in "/home/thomas/.badevops/lib/autocomplete.d/"*; do source "$__bootstrap_autofile"; done
