#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/thomas/applications/google-cloud-sdk/path.zsh.inc' ]; then source '/home/thomas/applications/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/thomas/applications/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/thomas/applications/google-cloud-sdk/completion.zsh.inc'; fi

function powerline_precmd() {
    PS1="$($HOME/go/bin/powerline-go -error $? -shell zsh -cwd-max-dir-size 5 -modules user,host,cwd,gitlite,jobs,exit)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi


xdebug-cli-on(){
	export XDEBUG_CONFIG="idekey=PHPSTORM"
}

xdebug-cli-off(){
	unset XDEBUG_CONFIG
}

refresh-dot-files(){
	cd ~
	git pull origin master
}

surf(){
	vlc https://cams.cdn-surfline.com/wsc-east/ec-washoutcam.stream/chunklist.m3u8
}
